version: '2'

services:
  web:
    image: leapar/librenms:1.27
    ports:
      - "80:80"
    volumes:
      - ./directory/logs:/opt/librenms/logs \
      - ./directory/rrd:/opt/librenms/rrd \
    environment:
      - DB_HOST=db
      - DB_NAME=librenms
      - DB_USER=librenms
      - DB_PASS=wangwang
      - POLLERS=16
      - BASE_URL=http://localhost:9080
    links:
      - mysql:db
  mysql:
    image: mysql:5.6
    command: --sql-mode=""
    ports:
      - "3306:3306"
    volumes:
      - /directory/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wangwang
